# this rule require pdoc3. To install it, run "pip3 install pdoc3"

runExample:
	bash -c "./Game.py ai.playerTest.myPlayer ai.playerTest.myPlayer"

runAstar:
	bash -c "./Game.py ai.playerTest.myPlayerAstar ai.playerTest.myPlayerAstar"

